root: ./

structure:
  readme: docs/README.md
  summary: docs/SUMMARY.md

redirects:
  these-pages-will-not-be-moved/this-page-will-be-redirected-before-the-move: docs/these-pages-will-be-moved/this-page-will-have-a-page-redirected-to-it.md
  test1: these-pages-will-be-moved/this-page-will-have-a-page-redirected-to-it.md
  test2: docs/these-pages-will-be-moved/this-page-will-have-a-page-redirected-to-it.md 
